import 'package:flutter/material.dart';
void main() => runApp(const OttoApp());

class AC {static const C P=Color(0xFF00FF88),BG=Color(0xFF1A1A2E),PN=Color(0xFF16213E);}
class PKA extends StatelessWidget {const PKA({super.key});@override Widget build(BuildContext context)=>MaterialApp(title:'Otto',debugShowCheckedModeBanner:false,theme:ThemeData.dark().copyWith(scaffoldBackgroundColor:AC.BG,primaryColor:AC.P),home:const MN());}
class MN extends StatefulWidget{const MN({super.key});@override State<MN>createState()=>_MNState();}
class _MNState extends State<MN>{int i=0;List M=[];List B=[];
@override Widget build(BuildContext context)=>Scaffold(body:IndexedStack(index:i,children:[RP(M,B),SP('Meine 2 Karten',(c)=>setState(()=>M=c)),SP('Tisch (5)',(c)=>setState(()=>B=c))]),
bottomNavigationBar:BottomNavigationBar(currentIndex:i,onTap:(x)=>setState(()=>i=x),selectedItemColor:AC.P,backgroundColor:AC.PN,items:const[BottomNavigationBarItem(icon:Icon(Icons.poker_chip),label:'Empfehlung'),BottomNavigationBarItem(icon:Icon(Icons.person),label:'Meine 2'),BottomNavigationBarItem(icon:Icon(Icons.table_restaurant),label:'Tisch (5)')]));}}

class RP extends StatefulWidget{final List M,B;const RP(this.M,this.B,{super.key});@override State<RP> createState()=>_RPState();}
class _RPState extends State<RP>{int p=2,hr=0;double pt=100,tc=20,ss=200;String r='';final ps=['BB','SB','BTN','CO','MP','UTG'];
void _rec(){int st=widget.B.isEmpty?0:widget.B.length<4?1:widget.B.length<5?2:3;double sc=(hr/8)*0.5+((6-p)/6)*0.3+0.2;if(ss<20)sc-=0.2;double po=tc>0?tc/(pt+tc):0;bool pf=po<(hr/8);if(tc>ss*0.4)r='FOLD';else if(sc>0.7)r=ss<40?'ALL-IN':'RAISE';else if(sc>0.45)r=pf?'CALL':'CHECK';else r=tc==0?'CHECK':'FOLD';setState((){});}
void _ev(){if(widget.M.isEmpty){hr=0;return;}List rs=[...widget.M.map((c)=>c['r']),...widget.B.map((c)=>c['r'])];List ss_=[...widget.M.map((c)=>c['s']),...widget.B.map((c)=>c['s'])];Map rc={},sc={};for(var x in rs)rc[x]=(rc[x]??0)+1;for(var x in ss_)sc[x]=(sc[x]??0)+1;if(sc.values.any((c)=>c>=5))hr=5;else if(rc.values.any((c)=>c>=4))hr=7;else if(rc.values.any((c)=>c==3)&&rc.values.any((c)>=2))hr=6;else if(rc.values.any((c)=>c==3))hr=3;else{hr=rc.values.where((c)=>c==2).length>=2?2:(rc.values.any((c)=>c==2)?1:0);}}
@override Widget build(BuildContext context){_ev();String sn=widget.B.isEmpty?'Preflop':widget.B.length==3?'Flop':widget.B.length==4?'Turn':'River';return Scaffold(appBar:AppBar(title:const Row(mainAxisSize:MainAxisSize.min,children:[Text('🦦 '),Text('Otto',style:TextStyle(fontWeight:FontWeight.bold))]),centerTitle:true),
body:SingleChildScrollView(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[
_('🦦 MEINE 2 KARTEN',widget.M),_('♠♣ TISCH: ${widget.B.length} Karten',widget.B),
if(hr>0||widget.M.isNotEmpty)Container(padding:const EdgeInsets.all(12),margin:const EdgeInsets.only(bottom:12),decoration:BoxDecoration(color:AC.P.withOpacity(0.2),borderRadius:BorderRadius.circular(8)),
child:Row(mainAxisAlignment:MainAxisAlignment.center,children:[const Icon(Icons.analytics,color:AC.P),const SizedBox(width:8),Text('Hand: ${_h(hr)} | $sn',style:TextStyle(color:AC.P,fontSize:16,fontWeight:FontWeight.bold))])),
if(r.isNotEmpty)Container(padding:const EdgeInsets.all(24),decoration:BoxDecoration(gradient:LinearGradient(colors:r=='ALL-IN'?[Colors.red,Colors.red.shade700]:[AC.P,AC.P.withOpacity(0.7)],begin:Alignment.topLeft,end:Alignment.bottomRight),borderRadius:BorderRadius.circular(16)),
child:Column(children:[const Text('EMPFEHLUNG',style:TextStyle(fontSize:14,color:Colors.black54)),Text(r,style:const TextStyle(fontSize:42,fontWeight:FontWeight.bold,color:Colors.black))])),
const SizedBox(height:20),_d('Position',p,ps,(x)=>setState(()=>p=x)),_s('Pot',pt,500,(x)=>setState(()=>pt=x)),_s('Zu zahlen',tc,200,(x)=>setState(()=>tc=x)),_s('Stack',ss,500,(x)=>setState(()=>ss=x)),const SizedBox(height:20),
ElevatedButton(onPressed:_rec,style:ElevatedButton.styleFrom(backgroundColor:AC.P,foregroundColor:Colors.black,padding:const EdgeInsets.all(16),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(12))),
child:const Text('🎯 EMPFEHLUNG',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)))]))));}}
Widget _(String t,List c)=>Container(margin:const EdgeInsets.only(bottom:12),padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:AC.PN,borderRadius:BorderRadius.circular(8)),
child:Column(children:[Text(t,style:const TextStyle(color:Colors.grey,fontSize:12)),const SizedBox(height:8),
c.isEmpty?const Text('Keine',style:TextStyle(color:Colors.grey)):Wrap(alignment:WrapAlignment.center,spacing:8,runSpacing:8,children:c.map((x){bool r=x['s']=='♥'||x['s']=='♦';return Container(padding:const EdgeInsets.symmetric(horizontal:16,vertical:10),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(6),border:Border.all(color:r?Colors.red:Colors.black,width:2)),child:Text('${x['r']}${x['s']}',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold,color:r?Colors.red:Colors.black));}).toList())]));}
Widget _d(String l,int v,List I,Function f)=>Padding(padding:const EdgeInsets.only(bottom:8),child:Row(children:[SizedBox(width:90,child:Text('$l:',style:const TextStyle(color:Colors.white70))),Expanded(child:Container(padding:const EdgeInsets.symmetric(horizontal:12),decoration:BoxDecoration(color:AC.PN,borderRadius:BorderRadius.circular(8)),
child:DropdownButton<int>(value:v,isExpanded:true,underline:const SizedBox(),dropdownColor:AC.PN,items:List.generate(I.length,(x)=>DropdownMenuItem(value:x,child:Text(I[x]))),onChanged:(y)=>f(y))))]));}
Widget _s(String l,double v,double m,Function f)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('$l: \$${v.toStringAsFixed(0)}',style:const TextStyle(color:Colors.white70,fontSize:13)),SliderTheme(data:SliderTheme.of(context).copyWith(activeTrackColor:AC.P,thumbColor:AC.P,inactiveTrackColor:Colors.grey.shade800),child:Slider(value:v,min:0,max:m,onChanged:(x)=>f(x)))]);
String _h(int r)=>['High Card','Pair','Two Pair','Three of Kind','Straight','Flush','Full House','Four of Kind','Straight Flush'][r.clamp(0,8)];}

class SP extends StatefulWidget{final String t;final Function(List) onDetected;const SP(this.t,this.onDetected,{super.key});@override State<SP> createState()=>_SPState();}
class _SPState extends State<SP>{bool scan=false;List c=[];void _s(){setState(()=>scan=true);Future.delayed(Duration(seconds:this.t.contains('Tisch')?3:2),(){List rs=['A','K','Q','J','10','9','8','7','6','5','4','3','2'];List ss=['♠','♥','♦','♣'];c=this.t.contains('Tisch')?List.generate(5,(i)=>{int m=DateTime.now().millisecond+i;return{'r':rs[m%13],'s':ss[m%4]};}):[{'r':rs[DateTime.now().millisecond%13],'s':ss[DateTime.now().second%4]},{'r':rs[DateTime.now().second%13],'s':ss[DateTime.now().millisecond%4]}];widget.onDetected(c);setState(()=>scan=false);});}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(widget.t)),body:Column(children:[
Expanded(child:Container(margin:const EdgeInsets.all(16),decoration:BoxDecoration(color:Colors.black,borderRadius:BorderRadius.circular(16),border:Border.all(color:scan?AC.P:Colors.grey,width:2)),
child:Center(child:scan?Column(mainAxisAlignment:MainAxisAlignment.center,children:[const CircularProgressIndicator(color:AC.P),const SizedBox(height:16),Text('Scanne...',style:TextStyle(color:AC.P,fontSize:18)),const Text('Halte Karten vor die Kamera',style:TextStyle(color:Colors.grey,fontSize:14))]):Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(this.t.contains('Tisch')?Icons.table_restaurant(Icons.table_restaurant):Icons.person,size:64,color:Colors.grey),const SizedBox(height:16),const Text('Bereit',style:TextStyle(color:Colors.grey,fontSize:18))])))),
if(c.isNotEmpty)Container(margin:const EdgeInsets.symmetric(horizontal:16),padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:AC.PN,borderRadius:BorderRadius.circular(12)),
child:Column(children:[Text('ERKANNTE KARTEN: ${c.length}',style:const TextStyle(color:Colors.grey,fontSize:12)),const SizedBox(height:12),Wrap(alignment:WrapAlignment.center,spacing:8,runSpacing:8,children:c.map((x){bool r=x['s']=='♥'||x['s']=='♦';return Container(padding:const EdgeInsets.symmetric(horizontal:20,vertical:12),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(8),border:Border.all(color:r?Colors.red:Colors.black,width:2)),child:Text('${x['r']}${x['s']}',style:TextStyle(fontSize:32,fontWeight:FontWeight.bold,color:r?Colors.red:Colors.black)));}).toList())]))),
const SizedBox(height:16),Padding(padding:const EdgeInsets.all(16),child:ElevatedButton.icon(onPressed:scan?null:_s,icon:Icon(scan?Icons.hourglass_top:Icons.camera_alt),label:Text(scan?'Scanne...':'SCANNEN'),
style:ElevatedButton.styleFrom(backgroundColor:AC.P,foregroundColor:Colors.black,padding:const EdgeInsets.all(16),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(12))))),const Text('Halte Karten vor die Kamera',style:TextStyle(color:Colors.grey)),const SizedBox(height:16)]));}
